-- Utshorgo schema for Supabase
-- Paste into Supabase → SQL Editor → Run

create table if not exists public.resellers (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  tagline text,
  badge text default 'New',
  rating numeric(3,2) default 0,
  followers integer default 0,
  item_count integer default 0,
  photo text,
  created_at timestamptz default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  type text not null default 'product',          -- 'product' | 'service'
  status text not null default 'pending',        -- 'pending' | 'approved' | 'rejected'
  price numeric(10,2) not null,                  -- retail price buyers pay
  reseller_price numeric(10,2),                  -- wholesale price resellers pay
  category text not null,
  visual text,
  image_url text,
  stock integer default 0,
  reseller_id bigint references public.resellers(id) on delete set null,
  reseller_name text,
  submitted_by text,
  review_note text,
  reviewed_at timestamptz,
  rating numeric(3,2) default 0,
  reviews integer default 0,
  is_new boolean default false,
  on_sale boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique,
  items jsonb not null,
  total numeric(10,2) not null,
  status text default 'processing',
  created_at timestamptz default now()
);

-- Reseller buys stock from a seller at wholesale price (decrements products.stock)
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  reseller_name text not null default 'My Store',
  listing_id bigint references public.products(id) on delete set null,
  listing_name text not null,
  listing_type text not null default 'product',
  seller_name text,
  qty integer not null check (qty > 0),
  unit_cost numeric(10,2) not null,
  total_cost numeric(10,2) not null,
  purchased_at timestamptz default now()
);

-- Reseller sells previously purchased stock; profit = (unit_price - unit_cost) * qty
create table if not exists public.resales (
  id bigint generated by default as identity primary key,
  purchase_id bigint references public.purchases(id) on delete cascade,
  listing_id bigint references public.products(id) on delete set null,
  listing_name text not null,
  reseller_name text,
  qty integer not null check (qty > 0),
  unit_cost numeric(10,2) not null,
  unit_price numeric(10,2) not null,
  revenue numeric(10,2) not null,
  profit numeric(10,2) not null,
  sold_at timestamptz default now()
);

alter table public.resellers enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.purchases enable row level security;
alter table public.resales enable row level security;

-- Public read access to the approved catalog only
create policy "Public read resellers" on public.resellers for select using (true);
create policy "Public read approved products" on public.products for select using (status = 'approved');
create policy "Public read orders" on public.orders for select using (true);

-- Orders can be created by anyone through the server (service role bypasses RLS)
create policy "Anyone can create orders" on public.orders for insert with check (true);
create policy "Service-role writes purchases" on public.purchases for all using (true) with check (true);
create policy "Service-role writes resales" on public.resales for all using (true) with check (true);

create index if not exists products_status_idx on public.products (status);
create index if not exists products_type_idx on public.products (type);
create index if not exists products_category_idx on public.products (category);
create index if not exists products_name_idx on public.products using gin (to_tsvector('english', name));

-- Lightweight admin gate: only uids in this table can moderate through the
-- server's admin check. Add your own uid after enabling Supabase Auth.
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
