-- Utshorgo schema for Supabase
-- Paste into Supabase → SQL Editor → Run

create table if not exists public.resellers (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  tagline text,
  badge text default 'New',
  rating numeric(3,2) default 0,
  followers integer default 0,
  item_count integer default 0,
  photo text,
  created_at timestamptz default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10,2) not null,
  category text not null,
  visual text,
  reseller_id bigint references public.resellers(id) on delete set null,
  rating numeric(3,2) default 0,
  reviews integer default 0,
  is_new boolean default false,
  on_sale boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique,
  items jsonb not null,
  total numeric(10,2) not null,
  status text default 'processing',
  created_at timestamptz default now()
);

alter table public.resellers enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;

-- Public read access
create policy "Public read resellers" on public.resellers for select using (true);
create policy "Public read products" on public.products for select using (true);
create policy "Public read orders" on public.orders for select using (true);

-- Orders can be created by anyone through the server (service role bypasses RLS)
create policy "Anyone can create orders" on public.orders for insert with check (true);

create index if not exists products_category_idx on public.products (category);
create index if not exists products_name_idx on public.products using gin (to_tsvector('english', name));
