export const seedResellers = [
  {
    id: 1,
    name: 'Studio Noma',
    location: 'Copenhagen',
    tagline: 'Objects & form',
    badge: 'Verified',
    rating: 4.9,
    followers: 12400,
    item_count: 128,
    photo: 'photo-one',
  },
  {
    id: 2,
    name: 'Maison Sunday',
    location: 'Paris',
    tagline: 'Slow living',
    badge: 'Verified',
    rating: 4.8,
    followers: 8100,
    item_count: 86,
    photo: 'photo-two',
  },
  {
    id: 3,
    name: 'Analog Club',
    location: 'London',
    tagline: 'Vintage tech',
    badge: 'Verified',
    rating: 5.0,
    followers: 5700,
    item_count: 214,
    photo: 'photo-three',
  },
  {
    id: 4,
    name: 'Reframe Archive',
    location: 'Seoul',
    tagline: 'Fashion edit',
    badge: 'Rising star',
    rating: 4.9,
    followers: 18600,
    item_count: 62,
    photo: 'photo-four',
  },
];

const base = {
  type: 'product',
  status: 'approved',
  stock: 24,
  image_url: null,
  submitted_by: 'Utshorgo Curators',
  review_note: null,
};

export const seedProducts = [
  {
    ...base,
    id: 1,
    name: 'Arc travel tote',
    description: 'Structured carry for long weekends. Water-resistant canvas, vegetable-tanned leather handles.',
    price: 189,
    reseller_price: 118,
    category: 'Objects',
    visual: 'image-lamp',
    reseller_id: 1,
    reseller_name: 'Studio Noma',
    rating: 4.8,
    reviews: 214,
    is_new: true,
    on_sale: false,
  },
  {
    ...base,
    id: 2,
    name: 'Meridian field watch',
    description: '38mm automatic with a sapphire crystal and a strap that ages better than most of us.',
    price: 340,
    reseller_price: 205,
    category: 'Objects',
    visual: 'image-watch',
    reseller_id: 3,
    reseller_name: 'Analog Club',
    rating: 4.9,
    reviews: 168,
    is_new: false,
    on_sale: true,
  },
  {
    ...base,
    id: 3,
    name: 'Transistor radio FM',
    description: 'Restored 1970s receiver. Warm analog sound, one honest speaker, zero notifications.',
    price: 96,
    reseller_price: 58,
    category: 'Vintage',
    visual: 'image-radio',
    reseller_id: 3,
    reseller_name: 'Analog Club',
    rating: 4.7,
    reviews: 89,
    is_new: false,
    on_sale: false,
  },
  {
    ...base,
    id: 4,
    name: 'Field notes library',
    description: 'Complete bound set of the first print runs. Shelf-ready, coffee-stain approved.',
    price: 54,
    reseller_price: 31,
    category: 'Vintage',
    visual: 'image-book',
    reseller_id: 2,
    reseller_name: 'Maison Sunday',
    rating: 4.6,
    reviews: 132,
    is_new: false,
    on_sale: false,
  },
  {
    ...base,
    id: 5,
    name: 'Terra ceramic vase',
    description: 'Wheel-thrown stoneware with a reactive glaze. No two pour the same.',
    price: 128,
    reseller_price: 74,
    category: 'Objects',
    visual: 'image-ceramic',
    reseller_id: 2,
    reseller_name: 'Maison Sunday',
    rating: 4.8,
    reviews: 76,
    is_new: true,
    on_sale: false,
  },
  {
    ...base,
    id: 6,
    name: 'Orbit frame set',
    description: 'Three asymmetric brass frames for the gallery wall you keep promising.',
    price: 72,
    reseller_price: 44,
    category: 'Objects',
    visual: 'image-frames',
    reseller_id: 1,
    reseller_name: 'Studio Noma',
    rating: 4.5,
    reviews: 58,
    is_new: false,
    on_sale: true,
  },
  {
    ...base,
    id: 7,
    name: 'Move with intent poster',
    description: 'Riso-printed manifesto in three inks. Ships in a tube, argues on your wall.',
    price: 32,
    reseller_price: 18,
    category: 'Digital',
    visual: 'image-poster',
    reseller_id: 4,
    reseller_name: 'Reframe Archive',
    rating: 4.9,
    reviews: 341,
    is_new: true,
    on_sale: false,
  },
  {
    ...base,
    id: 8,
    name: 'Waveform speaker',
    description: 'Pocket analog recorder and speaker. Records 90 minutes of ambience per side.',
    price: 210,
    reseller_price: 132,
    category: 'Digital',
    visual: 'image-sound',
    reseller_id: 4,
    reseller_name: 'Reframe Archive',
    rating: 4.7,
    reviews: 97,
    is_new: true,
    on_sale: false,
  },
  /* ---------------------------- Services ---------------------------- */
  {
    ...base,
    id: 9,
    type: 'service',
    name: 'Personal styling session',
    description: 'One hour with a working stylist. Closet audit, outfit formulas, and a shoppable list afterwards.',
    price: 85,
    reseller_price: 55,
    category: 'Wearables',
    visual: 'image-style',
    reseller_id: 4,
    reseller_name: 'Reframe Archive',
    rating: 4.9,
    reviews: 64,
    is_new: true,
    on_sale: false,
    stock: 12,
  },
  {
    ...base,
    id: 10,
    type: 'service',
    name: 'Furniture restoration',
    description: 'We strip, sand, and re-oil your tired heirloom. Pickup and delivery included within the city.',
    price: 240,
    reseller_price: 150,
    category: 'Objects',
    visual: 'image-restore',
    reseller_id: 2,
    reseller_name: 'Maison Sunday',
    rating: 4.8,
    reviews: 41,
    is_new: false,
    on_sale: false,
    stock: 6,
  },
  {
    ...base,
    id: 11,
    type: 'service',
    name: 'Vintage tech repair',
    description: 'Diagnosis plus repair for radios, cameras, and turntables. Original parts whenever possible.',
    price: 65,
    reseller_price: 40,
    category: 'Vintage',
    visual: 'image-repair',
    reseller_id: 3,
    reseller_name: 'Analog Club',
    rating: 4.9,
    reviews: 118,
    is_new: true,
    on_sale: false,
    stock: 20,
  },
  {
    ...base,
    id: 12,
    type: 'service',
    name: 'Product photography day',
    description: 'Half-day studio session for up to 15 SKUs. Retouched hero shots delivered in 72 hours.',
    price: 320,
    reseller_price: 210,
    category: 'Digital',
    visual: 'image-photo',
    reseller_id: 1,
    reseller_name: 'Studio Noma',
    rating: 5.0,
    reviews: 27,
    is_new: true,
    on_sale: false,
    stock: 4,
  },
  /* ----------------- Pending submissions (admin queue) --------------- */
  {
    ...base,
    id: 101,
    status: 'pending',
    name: 'Lumen desk lamp',
    description: 'Brushed steel task lamp with a warm 2700K LED and a dimmer you can actually find in the dark.',
    price: 149,
    reseller_price: 92,
    category: 'Objects',
    visual: 'image-lamp',
    reseller_id: 1,
    reseller_name: 'Studio Noma',
    submitted_by: 'Studio Noma',
    rating: 0,
    reviews: 0,
    is_new: true,
    on_sale: false,
    stock: 30,
  },
  {
    ...base,
    id: 102,
    status: 'pending',
    type: 'service',
    name: 'Closet detox intensive',
    description: 'Two-hour in-home wardrobe edit. We keep what earns its place and consign the rest on your behalf.',
    price: 180,
    reseller_price: 120,
    category: 'Wearables',
    visual: 'image-style',
    reseller_id: 4,
    reseller_name: 'Reframe Archive',
    submitted_by: 'Reframe Archive',
    rating: 0,
    reviews: 0,
    is_new: true,
    on_sale: false,
    stock: 8,
  },
  {
    ...base,
    id: 103,
    status: 'pending',
    name: 'Dune linen throw',
    description: 'Stonewashed Belgian linen in three neutrals. Gets softer with every wash, like good denim.',
    price: 95,
    reseller_price: 52,
    category: 'Objects',
    visual: 'image-ceramic',
    reseller_id: 2,
    reseller_name: 'Maison Sunday',
    submitted_by: 'Maison Sunday',
    rating: 0,
    reviews: 0,
    is_new: true,
    on_sale: false,
    stock: 40,
  },
];

/* --------------- Demo reseller activity (purchases + resales) -------- */

export const seedPurchases = [
  {
    id: 1,
    reseller_name: 'My Store',
    listing_id: 1,
    listing_name: 'Arc travel tote',
    listing_type: 'product',
    seller_name: 'Studio Noma',
    qty: 5,
    unit_cost: 118,
    total_cost: 590,
    purchased_at: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 2,
    reseller_name: 'My Store',
    listing_id: 7,
    listing_name: 'Move with intent poster',
    listing_type: 'product',
    seller_name: 'Reframe Archive',
    qty: 10,
    unit_cost: 18,
    total_cost: 180,
    purchased_at: '2026-09-05T09:30:00.000Z',
  },
  {
    id: 3,
    reseller_name: 'My Store',
    listing_id: 11,
    listing_name: 'Vintage tech repair',
    listing_type: 'service',
    seller_name: 'Analog Club',
    qty: 4,
    unit_cost: 40,
    total_cost: 160,
    purchased_at: '2026-09-10T14:00:00.000Z',
  },
];

export const seedResales = [
  {
    id: 1,
    purchase_id: 1,
    listing_id: 1,
    listing_name: 'Arc travel tote',
    qty: 2,
    unit_cost: 118,
    unit_price: 175,
    revenue: 350,
    profit: 114,
    sold_at: '2026-09-08T16:20:00.000Z',
  },
  {
    id: 2,
    purchase_id: 2,
    listing_id: 7,
    listing_name: 'Move with intent poster',
    qty: 6,
    unit_cost: 18,
    unit_price: 29,
    revenue: 174,
    profit: 66,
    sold_at: '2026-09-12T11:45:00.000Z',
  },
];
