export const seedResellers = [
  {
    id: 1,
    name: 'Studio Noma',
    location: 'Copenhagen',
    tagline: 'Objects & form',
    badge: 'Rising star',
    rating: 4.9,
    followers: 12400,
    item_count: 128,
    photo: 'photo-one',
  },
  {
    id: 2,
    name: 'Maison Sunday',
    location: 'Paris',
    tagline: 'Slow living',
    badge: 'Verified',
    rating: 4.8,
    followers: 8100,
    item_count: 86,
    photo: 'photo-two',
  },
  {
    id: 3,
    name: 'Analog Club',
    location: 'London',
    tagline: 'Vintage tech',
    badge: 'Verified',
    rating: 5.0,
    followers: 5700,
    item_count: 214,
    photo: 'photo-three',
  },
  {
    id: 4,
    name: 'Reframe Archive',
    location: 'Seoul',
    tagline: 'Fashion edit',
    badge: 'Rising star',
    rating: 4.9,
    followers: 18600,
    item_count: 62,
    photo: 'photo-four',
  },
];

export const seedProducts = [
  {
    id: 1,
    name: 'Arc travel tote',
    description: 'Structured carry for long weekends. Water-resistant canvas, vegetable-tanned leather handles.',
    price: 189,
    category: 'Objects',
    visual: 'image-lamp',
    reseller_id: 1,
    reseller_name: 'Studio Noma',
    rating: 4.8,
    reviews: 214,
    is_new: true,
    on_sale: false,
  },
  {
    id: 2,
    name: 'Meridian field watch',
    description: '38mm automatic with a sapphire crystal and a strap that ages better than most of us.',
    price: 340,
    category: 'Objects',
    visual: 'image-watch',
    reseller_id: 3,
    reseller_name: 'Analog Club',
    rating: 4.9,
    reviews: 168,
    is_new: false,
    on_sale: true,
  },
  {
    id: 3,
    name: 'Transistor radio FM',
    description: 'Restored 1970s receiver. Warm analog sound, one honest speaker, zero notifications.',
    price: 96,
    category: 'Vintage',
    visual: 'image-radio',
    reseller_id: 3,
    reseller_name: 'Analog Club',
    rating: 4.7,
    reviews: 89,
    is_new: false,
    on_sale: false,
  },
  {
    id: 4,
    name: 'Field notes library',
    description: 'Complete bound set of the first print runs. Shelf-ready, coffee-stain approved.',
    price: 54,
    category: 'Vintage',
    visual: 'image-book',
    reseller_id: 2,
    reseller_name: 'Maison Sunday',
    rating: 4.6,
    reviews: 132,
    is_new: false,
    on_sale: false,
  },
  {
    id: 5,
    name: 'Terra ceramic vase',
    description: 'Wheel-thrown stoneware with a reactive glaze. No two pour the same.',
    price: 128,
    category: 'Objects',
    visual: 'image-ceramic',
    reseller_id: 2,
    reseller_name: 'Maison Sunday',
    rating: 4.8,
    reviews: 76,
    is_new: true,
    on_sale: false,
  },
  {
    id: 6,
    name: 'Orbit frame set',
    description: 'Three asymmetric brass frames for the gallery wall you keep promising.',
    price: 72,
    category: 'Objects',
    visual: 'image-frames',
    reseller_id: 1,
    reseller_name: 'Studio Noma',
    rating: 4.5,
    reviews: 58,
    is_new: false,
    on_sale: true,
  },
  {
    id: 7,
    name: 'Move with intent poster',
    description: 'Riso-printed manifesto in three inks. Ships in a tube, argues on your wall.',
    price: 32,
    category: 'Digital',
    visual: 'image-poster',
    reseller_id: 4,
    reseller_name: 'Reframe Archive',
    rating: 4.9,
    reviews: 341,
    is_new: true,
    on_sale: false,
  },
  {
    id: 8,
    name: 'Waveform speaker',
    description: 'Pocket analog recorder and speaker. Records 90 minutes of ambience per side.',
    price: 210,
    category: 'Digital',
    visual: 'image-sound',
    reseller_id: 4,
    reseller_name: 'Reframe Archive',
    rating: 4.7,
    reviews: 97,
    is_new: true,
    on_sale: false,
  },
];
